export interface Iteam {
    _id: String,
    position: String,
    points: String,
    name: String,
    logo: String,
    driver1: String,
    driver2: String,
    carImage: String,
    logo2: String,
    base : String,
    teamChief: String,
    chassis: String,
    powerUnit: String,
    teamEntry: String,
    worldTitles: String,
    poles: String,
    fastestLaps: String,
    driver1Image: String,
    driver2Image: String,
}