export interface Idriver {
    _id: String,
    name: String,
    number: String,
    points: String,
    flag: String,
    team: String,
    image1: String,
    country: String,
    podiums: String,
    gps: String,
    worldtitles: String,
    date: String,
    birth: String,
    image2: String,
    casco: String,
    position: String,
}